// ═══════════════════════════════════════════════════════════════
//   Volt — service worker  (GENERATED by scripts/gen-sw.mjs — do not edit)
//   Cache-first for the app shell + vendored libraries, so Volt is
//   fully usable offline after the first visit and launches as an
//   installable PWA (own window, own icon, no browser tab).
//
//   The cache name is a SHA-256 of the app shell's file contents:
//   any edit to app.js / css / html / vendor files changes it, which
//   makes the browser reinstall the worker and re-precache everything
//   fresh under the new name (older caches are purged on activate).
//
//   VERSION is the human-visible release (from the VERSION file); the
//   version banner compares it against the installed bundle's version
//   and shows the CHANGELOG diff in a tooltip.
//   ═══════════════════════════════════════════════════════════════ */
"use strict";

const CACHE = "volt-d36b2a842995";
const VERSION = "1.0.1";
const ASSETS = [
  "./",
  "./index.html",
  "./css/style.css",
  "./js/utils.js",
  "./js/annotations.js",
  "./js/ai.js",
  "./js/app.js",
  "./js/ocr.js",
  "./js/sample-data.js",
  "./js/voice.js",
  "./js/office-export.js",
  "./vendor/pdf.min.mjs",
  "./vendor/pdf.worker.min.mjs",
  "./vendor/pdf-lib.min.js",
  "./vendor/tesseract/tesseract.min.js",
  "./vendor/tesseract/worker.min.js",
  "./vendor/tesseract/core/tesseract-core.wasm.js",
  "./vendor/tesseract/core/tesseract-core.wasm",
  "./vendor/tesseract/core/tesseract-core-simd.wasm.js",
  "./vendor/tesseract/core/tesseract-core-simd.wasm",
  "./vendor/tesseract/core/tesseract-core-lstm.wasm.js",
  "./vendor/tesseract/core/tesseract-core-lstm.wasm",
  "./vendor/tesseract/core/tesseract-core-simd-lstm.wasm.js",
  "./vendor/tesseract/core/tesseract-core-simd-lstm.wasm",
  "./vendor/tesseract/tessdata/eng.traineddata.gz",
  "./manifest.json",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./CHANGELOG.md"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// cache-first with network fallback; the app is fully static
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).then((res) => {
        if (res.ok && (res.type === "basic" || res.type === "default")) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy));
        }
        return res;
      });
    })
  );
});
